on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: ğŸš€ Deploy website on push

jobs:
  web-deploy-server1:
    name: ğŸ‰ Deploy to Server 1
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: ğŸ“‚ Sync files to Server 1
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: premierpipescode.erpcode.live
          username: premierpipescode@premierpipescode.erpcode.live
          password: ${{ secrets.ftp_password }}

  web-deploy-server2:
    name: ğŸ‰ Deploy to Server 2
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: ğŸ“‚ Sync files to Server 2
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: erp.premierpipeindustries.com
          username: premierpipeindustries@erp.premierpipeindustries.com
          password: x3@bYZ@[Ojyi

        